### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 2)

### ISSUE THREAD

**Issue by mtli77** [goodbye61/RI_l2g#1]
Hi, @goodbye61 
Thank you for sharing the project. During the evaluation step, something goes wrong:
```
Traceback (most recent call last):
  File "evaluate.py", line 377, in <module>
    train()
  File "evaluate.py", line 179, in train
    gcn3=gcn3, dilation=dilation)
ValueError: not enough values to unpack (expected 6, got 2)
```
This is because that in the `evaluation.py` script, the model need to return six values
```
pred, end_points, po, tr, po2, tr2 = MODEL.get_model(pointclouds_pl, FLAGS.num_pool, FLAGS.pool_knn1,
                                     is_training_pl, bn_decay=bn_decay, flag=flag_pl, flag2=flag2, flag3=flag3,gcn1=gcn1, gcn2=gcn2, gcn3=gcn3, dilation=dilation)
```
But in the `rinet.py` script, only have two values be returned.
 ```
return net, end_points
```
Could you please tell me what are the `po, tr, po2, tr2`?  
And which value should be returned in `rinet.py` during the evaluation process?

Best regards!

**Comment by goodbye61** [comment]
The returned values you mentioned (po, tr, po2, tr2) are just legacy, which is used for debugging. 
So, you can ignore them. 
I revised the code and committed so that you can clone the repo again.
