### ISSUE TITLE
How to train and evaluate on ShapeNet?

### ISSUE THREAD

**Issue by mtli77** [goodbye61/RI_l2g#2]
Hi, @goodbye61 
In the 3D Part Segmentation experiment in your paper,  you mentioned that you adopt the hierarchical point feature propagation strategy proposed by PointNet++. However the output values of each `encoder` layer of rinet are, e.g., `prev1, eig_vector, centering, out1, fps_points`, while the output values of each `pointnet_sa_module` layer are, e.g., `l1_xyz, l1_points, l1_indices`. 
Could you give more details of the correlation with their outputs? And which values of rinet are used for point feature propagation?

Best!

**Comment by goodbye61** [comment]
You can use output features into 'pointnet_sa_module' for each hierarchy as PointNet++ uses. 
For part segmentation, I’m going to organize the code and upload it later. 
Thanks.
